modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'Apache-2.0'
showAsResourcePack = false
issueTrackerURL = 'https://github.com/doonv/create_sa-tags/issues'
mods = [
    { modId = "create_sa_tags", version = "1.0.0", displayName = "Create Stuff 'N Additions Tag Fixes", description = "Adds missing tags to Create Stuff 'N Additions. Fixes enchanting, Dynamic Crosshair, and more.", logoFile = "pack.png", updateJSONURL = "https://modrinth.com/project/UDScyrfA/updates.json", displayURL = "https://modrinth.com/project/UDScyrfA" },
]

[[dependencies.create_sa_tags]]
    modId = "create_sa"
    mandatory = true
    versionRange = "[1,)"
    ordering = "NONE"
    side = "SERVER"
