name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

      - name: Build
        run: ./build.sh "$VERSION"

      - name: Create GitHub Release
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "$GITHUB_REF_NAME" \
            --generate-notes \
            build/create_sa-tags-*.{zip,jar}
          sleep 3
          gh release view "$GITHUB_REF_NAME" \
            --json body --jq .body > .github/changelog.txt
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish datapack 1.20.1 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: UDScyrfA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/create_sa-tags-${{ env.VERSION }}+1.20.1.zip
          version: ${{ env.VERSION }}+datapack-1.20.1
          version-type: release
          name: v${{ env.VERSION }} for Minecraft 1.20.1 (datapack)
          game-versions: 1.20.1
          changelog-file: .github/changelog.txt

      - name: Publish Forge 1.20.1 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: UDScyrfA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/create_sa-tags-${{ env.VERSION }}+1.20.1.jar
          version: ${{ env.VERSION }}+forge-1.20.1
          version-type: release
          name: v${{ env.VERSION }} for Forge 1.20.1
          game-versions: 1.20.1
          loaders: forge
          dependencies: |
            create_sa(required){modrinth:aq9qUUQG}

      - name: Publish datapack 1.21.1 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: UDScyrfA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/create_sa-tags-${{ env.VERSION }}+1.21.1.zip
          version: ${{ env.VERSION }}+datapack-1.21.1
          version-type: release
          name: v${{ env.VERSION }} for Minecraft 1.21.1 (datapack)
          game-versions: 1.21.1

      - name: Publish NeoForge 1.21.1 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: UDScyrfA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/create_sa-tags-${{ env.VERSION }}+1.21.1.jar
          version: ${{ env.VERSION }}+neoforge-1.21.1
          version-type: release
          name: v${{ env.VERSION }} for NeoForge 1.21.1
          game-versions: 1.21.1
          loaders: neoforge
          dependencies: |
            create_sa(required){modrinth:aq9qUUQG}
